AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - config/**/*
    - Gemfile

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
